name: Deploy to EKS

on:
  push:
    branches:
    - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Run Trivy vulnerability scanner in fs mode
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: fs
    #     scan-ref: .
    #     severity: CRITICA

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASS }}
    
    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # - name: Build Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: Dockerfile
    #     push: true
    #     tags: mohsin01/tesla-clone:${{ github.run_number }}

    - name: Build and push to ECR
      env:
       REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       REPOSITORY: my-repo
       IMAGE_TAG: latest
      run: |
       docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
       docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #      image-ref: docker.io/mohsin01/tesla-clone:${{ github.run_number }}
    #      format: table
    #      vuln-type: os,library
    #      severity: CRITICAL,HIGH

  deploy:
    needs: build-scan-push
    runs-on: ubuntu-latest
    steps:
    - name: Install kubectl
      uses: azure/setup-kubectl@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    -  name: Login to AWS ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1


    - name: Checkout manifests-k8s repository
      uses: actions/checkout@v2
      with:
        repository: mohsin-786/manifests-k8s
        path: manifests-k8s
        token: ${{ secrets.GH_TOKEN }}

    - name: Update deployment file
      env:
       REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       REPOSITORY: my-repo
       IMAGE_TAG: latest
      run: |
        cd manifests-k8s/
        git config user.email "mohsinabedeen78@gmail.com"
        git config user.name "mohsin-786"
        GIT_USER_NAME="mohsin-786"
        GIT_REPO_NAME="manifests-k8s"
        IMAGE_NAME="$REGISTRY/$REPOSITORY:$IMAGE_TAG"
        cd tesla-clone-manifests/
        sed -i "s|image: .*|image: $IMAGE_NAME|" tesla-manifest.yml
        git add tesla-manifest.yml
        git commit -m "Update deployment image to $IMAGE_NAME"
        git push https://${{ secrets.GH_TOKEN }}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main

    # - name: Update kubeconfig
    #   run: aws eks update-kubeconfig --name sins-cluster --region us-east-1

    - name: Apply the deployment file
      run: |
        cd manifests-k8s/tesla-clone-manifests/ && kubectl apply -f tesla-manifest.yml
        
      
    

