name: Deploy to EKS

on:
  push:
    branches:
    - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout repository
    #   uses: actions/checkout@v2

    # - name: Run Trivy vulnerability scanner in fs mode
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     scan-type: fs
    #     scan-ref: .
    #     severity: CRITICAL

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASS }}

    # - name: Build Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: Dockerfile
    #     push: true
    #     tags: mohsin01/tesla-clone:${{ github.run_number }}

    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: docker.io/mohsin01/tesla-clone:${{ github.run_number }}
    #     format: table
    #     vuln-type: os,library
    #     severity: CRITICAL,HIGH

  deploy:
    needs: build-scan-push
    runs-on: ubuntu-latest
    steps:
    # - name: Install kubectl
    #   uses: azure/setup-kubectl@v3

    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: us-east-1

    - name: Checkout manifests-k8s repository
      uses: actions/checkout@v2
      with:
        repository: mohsin-786/manifests-k8s
        path: manifests-k8s

    - name: List files
      run: ls -ltr manifests-k8s/


  # - name: Deploy to EKS
  #   uses: aws/eks@v1
  #   with:
  #     eks-cluster-name: <your-cluster-name>
  #     region: us-east-1
  #     command: kubectl apply -f <path-to-your-kubernetes-manifests>
